version: 2
updates:
- package-ecosystem: npm
  directory: "/examples/client-side-rendered/angular"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "01:00"
    timezone: "Europe/Berlin"
  open-pull-requests-limit: 20

- package-ecosystem: npm
  directory: "/examples/client-side-rendered/react"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "01:00"
    timezone: "Europe/Berlin"
  open-pull-requests-limit: 20

- package-ecosystem: npm
  directory: "/examples/client-side-rendered/svelte"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "01:00"
    timezone: "Europe/Berlin"
  open-pull-requests-limit: 20

- package-ecosystem: npm
  directory: "/examples/client-side-rendered/vue"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "01:00"
    timezone: "Europe/Berlin"
  open-pull-requests-limit: 20

- package-ecosystem: npm
  directory: "/examples/server-side-rendered/eleventy"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "01:00"
    timezone: "Europe/Berlin"
  open-pull-requests-limit: 20
