version: 2
updates:
- package-ecosystem: npm
  directory: "/examples/angular"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/examples/react"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/examples/svelte"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/examples/vue"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
